name: url_shorten
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animations: ^2.0.7
  animated_theme_switcher: ^2.0.8
  flex_color_scheme: ^7.1.2
  animated_bottom_navigation_bar: ^1.2.0
  flutter_animate: ^4.2.0
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  intl: ^0.18.1
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.17

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - logo/logo.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
