name: url_shorten
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animations: ^2.0.7
  animated_theme_switcher: ^2.0.8
  flex_color_scheme: ^7.1.2
  animated_bottom_navigation_bar: ^1.2.0
  flutter_animate: ^4.2.0
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
